### ISSUE TITLE
UI suggestions 

### ISSUE THREAD

**Issue by eliazzo** [fac27/tUdo#32]
'i' information toggle could be set to close automatically or appear when hovered over - it feels a bit awkward to manually open and close

**Comment by eliazzo** [comment]
It is possible to add empty items to the list, maybe this could be blocked?

**Comment by camelPhonso** [comment]
Good flag. We actually started off with it as an action on hover but changed it thinking of mobile-first design. It's just awkward to keep your finger on the screen and try to read through directions at the same time. But maybe there's a different compromise somewhere.

Definitely weren't supposed to allow empty tasks to be created so that will be fixed in the next commit for sure.

**Comment by eliazzo** [comment]
One thought I had was to use a setTimeout() so that it is visible for a few seconds and then disappears on its own
